// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"database/sql"
	"time"
)

type User struct {
	ID        string
	Username  string
	Verifier  []byte
	Role      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}
