// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: models.sql

package pg

import (
	"context"
	"time"

	"github.com/patraden/ya-practicum-gophkeeper/internal/domain/user"
)

const CreateUser = `-- name: CreateUser :one
INSERT INTO "user" (id, username, password, role, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (username) DO UPDATE
SET id = "user".id,
    username = "user".username,
    password = "user".password,
    role = "user".role,
    created_at = "user".created_at,
    updated_at = "user".updated_at
RETURNING id, username, password, role, created_at, updated_at
`

type CreateUserParams struct {
	ID        user.ID   `db:"id"`
	Username  string    `db:"username"`
	Password  []byte    `db:"password"`
	Role      user.Role `db:"role"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, CreateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
