// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pg

import (
	"time"

	"github.com/patraden/ya-practicum-gophkeeper/internal/domain/user"
)

type User struct {
	ID        user.ID   `db:"id"`
	Username  string    `db:"username"`
	Role      user.Role `db:"role"`
	Password  []byte    `db:"password"`
	Salt      []byte    `db:"salt"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}
