// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"time"

	"github.com/patraden/ya-practicum-gophkeeper/pkg/domain/user"
)

type User struct {
	ID         string
	Username   string
	Verifier   []byte
	Role       user.Role
	Salt       []byte
	Bucketname string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UsersServerToken struct {
	UserID string
	Token  string
	Ttl    int64
}
