// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"time"

	"github.com/patraden/ya-practicum-gophkeeper/pkg/domain/user"
)

type User struct {
	ID        string
	Username  string
	Verifier  string
	Role      user.Role
	Salt      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
