// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlite

import (
	"time"

	"github.com/patraden/ya-practicum-gophkeeper/pkg/domain/user"
)

type Secret struct {
	UserID          string
	SecretID        string
	SecretName      string
	VersionID       string
	ParentVersionID string
	FilePath        string
	SecretSize      int64
	SecretHash      []byte
	SecretDek       []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
	InSync          int64
}

type SecretMetum struct {
	UserID    string
	SecretID  string
	Meta      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID         string
	Username   string
	Verifier   []byte
	Role       user.Role
	Salt       []byte
	Bucketname string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UsersServerToken struct {
	UserID string
	Token  string
	Ttl    int64
}
