// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlite

import (
	"context"
	"time"

	"github.com/patraden/ya-practicum-gophkeeper/pkg/domain/user"
)

const countUser = `-- name: CountUser :one
SELECT count(*) FROM users
`

func (q *Queries) CountUser(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUser)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, verifier, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, username, verifier, role, created_at, updated_at
`

type CreateUserParams struct {
	ID        string
	Username  string
	Verifier  string
	Role      user.Role
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateUserRow struct {
	ID        string
	Username  string
	Verifier  string
	Role      user.Role
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Verifier,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Verifier,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
