// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophkeeper/v1/admin.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnsealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPiece      string                 `protobuf:"bytes,1,opt,name=key_piece,json=keyPiece,proto3" json:"key_piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_gophkeeper_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *UnsealRequest) GetKeyPiece() string {
	if x != nil {
		return x.KeyPiece
	}
	return ""
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SealStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=gophkeeper.v1.SealStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_gophkeeper_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *UnsealResponse) GetStatus() SealStatus {
	if x != nil {
		return x.Status
	}
	return SealStatus_SEAL_STATUS_UNSPECIFIED
}

func (x *UnsealResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gophkeeper_v1_admin_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x19gophkeeper/v1/admin.proto\x12\rgophkeeper.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1agophkeeper/v1/common.proto\"5\n" +
	"\rUnsealRequest\x12$\n" +
	"\tkey_piece\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bkeyPiece\"]\n" +
	"\x0eUnsealResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.SealStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2U\n" +
	"\fAdminService\x12E\n" +
	"\x06Unseal\x12\x1c.gophkeeper.v1.UnsealRequest\x1a\x1d.gophkeeper.v1.UnsealResponseB\xb9\x01\n" +
	"\x11com.gophkeeper.v1B\n" +
	"AdminProtoP\x01ZCgithub.com/patraden/ya-practicum-gophkeeper/api/gophkeeper/v1;proto\xa2\x02\x03GXX\xaa\x02\rGophkeeper.V1\xca\x02\rGophkeeper\\V1\xe2\x02\x19Gophkeeper\\V1\\GPBMetadata\xea\x02\x0eGophkeeper::V1b\x06proto3"

var (
	file_gophkeeper_v1_admin_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_admin_proto_rawDescData []byte
)

func file_gophkeeper_v1_admin_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_admin_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_admin_proto_rawDesc), len(file_gophkeeper_v1_admin_proto_rawDesc)))
	})
	return file_gophkeeper_v1_admin_proto_rawDescData
}

var file_gophkeeper_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gophkeeper_v1_admin_proto_goTypes = []any{
	(*UnsealRequest)(nil),  // 0: gophkeeper.v1.UnsealRequest
	(*UnsealResponse)(nil), // 1: gophkeeper.v1.UnsealResponse
	(SealStatus)(0),        // 2: gophkeeper.v1.SealStatus
}
var file_gophkeeper_v1_admin_proto_depIdxs = []int32{
	2, // 0: gophkeeper.v1.UnsealResponse.status:type_name -> gophkeeper.v1.SealStatus
	0, // 1: gophkeeper.v1.AdminService.Unseal:input_type -> gophkeeper.v1.UnsealRequest
	1, // 2: gophkeeper.v1.AdminService.Unseal:output_type -> gophkeeper.v1.UnsealResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_admin_proto_init() }
func file_gophkeeper_v1_admin_proto_init() {
	if File_gophkeeper_v1_admin_proto != nil {
		return
	}
	file_gophkeeper_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_admin_proto_rawDesc), len(file_gophkeeper_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_admin_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_admin_proto_depIdxs,
		MessageInfos:      file_gophkeeper_v1_admin_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_admin_proto = out.File
	file_gophkeeper_v1_admin_proto_goTypes = nil
	file_gophkeeper_v1_admin_proto_depIdxs = nil
}
