// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gophkeeper/v1/admin.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UnsealRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UnsealRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnsealRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UnsealRequestMultiError, or
// nil if none found.
func (m *UnsealRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UnsealRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for KeyPiece

	if len(errors) > 0 {
		return UnsealRequestMultiError(errors)
	}

	return nil
}

// UnsealRequestMultiError is an error wrapping multiple validation errors
// returned by UnsealRequest.ValidateAll() if the designated constraints
// aren't met.
type UnsealRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnsealRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnsealRequestMultiError) AllErrors() []error { return m }

// UnsealRequestValidationError is the validation error returned by
// UnsealRequest.Validate if the designated constraints aren't met.
type UnsealRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnsealRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnsealRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnsealRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnsealRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnsealRequestValidationError) ErrorName() string { return "UnsealRequestValidationError" }

// Error satisfies the builtin error interface
func (e UnsealRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnsealRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnsealRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnsealRequestValidationError{}

// Validate checks the field values on UnsealResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UnsealResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UnsealResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UnsealResponseMultiError,
// or nil if none found.
func (m *UnsealResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UnsealResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	// no validation rules for Message

	if len(errors) > 0 {
		return UnsealResponseMultiError(errors)
	}

	return nil
}

// UnsealResponseMultiError is an error wrapping multiple validation errors
// returned by UnsealResponse.ValidateAll() if the designated constraints
// aren't met.
type UnsealResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UnsealResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UnsealResponseMultiError) AllErrors() []error { return m }

// UnsealResponseValidationError is the validation error returned by
// UnsealResponse.Validate if the designated constraints aren't met.
type UnsealResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UnsealResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UnsealResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UnsealResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UnsealResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UnsealResponseValidationError) ErrorName() string { return "UnsealResponseValidationError" }

// Error satisfies the builtin error interface
func (e UnsealResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUnsealResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UnsealResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UnsealResponseValidationError{}
