// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophkeeper/v1/common.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_common_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_common_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_common_proto_rawDescGZIP(), []int{0}
}

type SealStatus int32

const (
	SealStatus_SEAL_STATUS_UNSPECIFIED SealStatus = 0
	SealStatus_SEAL_STATUS_SEALED      SealStatus = 1
	SealStatus_SEAL_STATUS_UNSEALED    SealStatus = 2
)

// Enum value maps for SealStatus.
var (
	SealStatus_name = map[int32]string{
		0: "SEAL_STATUS_UNSPECIFIED",
		1: "SEAL_STATUS_SEALED",
		2: "SEAL_STATUS_UNSEALED",
	}
	SealStatus_value = map[string]int32{
		"SEAL_STATUS_UNSPECIFIED": 0,
		"SEAL_STATUS_SEALED":      1,
		"SEAL_STATUS_UNSEALED":    2,
	}
)

func (x SealStatus) Enum() *SealStatus {
	p := new(SealStatus)
	*p = x
	return p
}

func (x SealStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SealStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_common_proto_enumTypes[1].Descriptor()
}

func (SealStatus) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_common_proto_enumTypes[1]
}

func (x SealStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SealStatus.Descriptor instead.
func (SealStatus) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_common_proto_rawDescGZIP(), []int{1}
}

type TemporaryCredentials struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`             // Temporary access key
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"` // Temporary secret key
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`            // Session token (required for auth)
	Expiration      string                 `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`                                    // Expiration timestamp (ISO8601)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TemporaryCredentials) Reset() {
	*x = TemporaryCredentials{}
	mi := &file_gophkeeper_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemporaryCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemporaryCredentials) ProtoMessage() {}

func (x *TemporaryCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemporaryCredentials.ProtoReflect.Descriptor instead.
func (*TemporaryCredentials) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *TemporaryCredentials) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *TemporaryCredentials) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *TemporaryCredentials) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *TemporaryCredentials) GetExpiration() string {
	if x != nil {
		return x.Expiration
	}
	return ""
}

var File_gophkeeper_v1_common_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1agophkeeper/v1/common.proto\x12\rgophkeeper.v1\x1a\x1bbuf/validate/validate.proto\"\xcf\x01\n" +
	"\x14TemporaryCredentials\x12+\n" +
	"\raccess_key_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vaccessKeyId\x123\n" +
	"\x11secret_access_key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fsecretAccessKey\x12,\n" +
	"\rsession_token\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fsessionToken\x12'\n" +
	"\n" +
	"expiration\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"expiration*N\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02*[\n" +
	"\n" +
	"SealStatus\x12\x1b\n" +
	"\x17SEAL_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEAL_STATUS_SEALED\x10\x01\x12\x18\n" +
	"\x14SEAL_STATUS_UNSEALED\x10\x02B\xba\x01\n" +
	"\x11com.gophkeeper.v1B\vCommonProtoP\x01ZCgithub.com/patraden/ya-practicum-gophkeeper/api/gophkeeper/v1;proto\xa2\x02\x03GXX\xaa\x02\rGophkeeper.V1\xca\x02\rGophkeeper\\V1\xe2\x02\x19Gophkeeper\\V1\\GPBMetadata\xea\x02\x0eGophkeeper::V1b\x06proto3"

var (
	file_gophkeeper_v1_common_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_common_proto_rawDescData []byte
)

func file_gophkeeper_v1_common_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_common_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_common_proto_rawDesc), len(file_gophkeeper_v1_common_proto_rawDesc)))
	})
	return file_gophkeeper_v1_common_proto_rawDescData
}

var file_gophkeeper_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gophkeeper_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gophkeeper_v1_common_proto_goTypes = []any{
	(UserRole)(0),                // 0: gophkeeper.v1.UserRole
	(SealStatus)(0),              // 1: gophkeeper.v1.SealStatus
	(*TemporaryCredentials)(nil), // 2: gophkeeper.v1.TemporaryCredentials
}
var file_gophkeeper_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_common_proto_init() }
func file_gophkeeper_v1_common_proto_init() {
	if File_gophkeeper_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_common_proto_rawDesc), len(file_gophkeeper_v1_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gophkeeper_v1_common_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_common_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_common_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_common_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_common_proto = out.File
	file_gophkeeper_v1_common_proto_goTypes = nil
	file_gophkeeper_v1_common_proto_depIdxs = nil
}
