// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophkeeper/v1/gophkeeper.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRole defines the access level of a user in the system.
type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_gophkeeper_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type SealStatus int32

const (
	SealStatus_SEAL_STATUS_UNSPECIFIED SealStatus = 0
	SealStatus_SEAL_STATUS_SEALED      SealStatus = 1
	SealStatus_SEAL_STATUS_UNSEALED    SealStatus = 2
)

// Enum value maps for SealStatus.
var (
	SealStatus_name = map[int32]string{
		0: "SEAL_STATUS_UNSPECIFIED",
		1: "SEAL_STATUS_SEALED",
		2: "SEAL_STATUS_UNSEALED",
	}
	SealStatus_value = map[string]int32{
		"SEAL_STATUS_UNSPECIFIED": 0,
		"SEAL_STATUS_SEALED":      1,
		"SEAL_STATUS_UNSEALED":    2,
	}
)

func (x SealStatus) Enum() *SealStatus {
	p := new(SealStatus)
	*p = x
	return p
}

func (x SealStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SealStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_gophkeeper_proto_enumTypes[1].Descriptor()
}

func (SealStatus) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_gophkeeper_proto_enumTypes[1]
}

func (x SealStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SealStatus.Descriptor instead.
func (SealStatus) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

type UnsealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPiece      string                 `protobuf:"bytes,1,opt,name=key_piece,json=keyPiece,proto3" json:"key_piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *UnsealRequest) GetKeyPiece() string {
	if x != nil {
		return x.KeyPiece
	}
	return ""
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        SealStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=gophkeeper.v1.SealStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *UnsealResponse) GetStatus() SealStatus {
	if x != nil {
		return x.Status
	}
	return SealStatus_SEAL_STATUS_UNSPECIFIED
}

func (x *UnsealResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=gophkeeper.v1.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=gophkeeper.v1.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=gophkeeper.v1.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

var File_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1egophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1bbuf/validate/validate.proto\"5\n" +
	"\rUnsealRequest\x12$\n" +
	"\tkey_piece\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bkeyPiece\"]\n" +
	"\x0eUnsealResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.SealStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\fLoginRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18@R\busername\x12&\n" +
	"\bpassword\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\b\x18\x80\x01R\bpassword\"k\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.gophkeeper.v1.UserRoleR\x04role\"\x92\x01\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x03R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\bR\bpassword\x125\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.gophkeeper.v1.UserRoleB\b\xbaH\x05\x82\x01\x02\x10\x01R\x04role\"n\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.gophkeeper.v1.UserRoleR\x04role*N\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02*[\n" +
	"\n" +
	"SealStatus\x12\x1b\n" +
	"\x17SEAL_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEAL_STATUS_SEALED\x10\x01\x12\x18\n" +
	"\x14SEAL_STATUS_UNSEALED\x10\x022U\n" +
	"\fAdminService\x12E\n" +
	"\x06Unseal\x12\x1c.gophkeeper.v1.UnsealRequest\x1a\x1d.gophkeeper.v1.UnsealResponse2\x9e\x01\n" +
	"\vUserService\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse\x12K\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponseB\xbe\x01\n" +
	"\x11com.gophkeeper.v1B\x0fGophkeeperProtoP\x01ZCgithub.com/patraden/ya-practicum-gophkeeper/api/gophkeeper/v1;proto\xa2\x02\x03GXX\xaa\x02\rGophkeeper.V1\xca\x02\rGophkeeper\\V1\xe2\x02\x19Gophkeeper\\V1\\GPBMetadata\xea\x02\x0eGophkeeper::V1b\x06proto3"

var (
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_v1_gophkeeper_proto_rawDescData
}

var file_gophkeeper_v1_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(UserRole)(0),            // 0: gophkeeper.v1.UserRole
	(SealStatus)(0),          // 1: gophkeeper.v1.SealStatus
	(*UnsealRequest)(nil),    // 2: gophkeeper.v1.UnsealRequest
	(*UnsealResponse)(nil),   // 3: gophkeeper.v1.UnsealResponse
	(*LoginRequest)(nil),     // 4: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),    // 5: gophkeeper.v1.LoginResponse
	(*RegisterRequest)(nil),  // 6: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil), // 7: gophkeeper.v1.RegisterResponse
}
var file_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	1, // 0: gophkeeper.v1.UnsealResponse.status:type_name -> gophkeeper.v1.SealStatus
	0, // 1: gophkeeper.v1.LoginResponse.role:type_name -> gophkeeper.v1.UserRole
	0, // 2: gophkeeper.v1.RegisterRequest.role:type_name -> gophkeeper.v1.UserRole
	0, // 3: gophkeeper.v1.RegisterResponse.role:type_name -> gophkeeper.v1.UserRole
	2, // 4: gophkeeper.v1.AdminService.Unseal:input_type -> gophkeeper.v1.UnsealRequest
	4, // 5: gophkeeper.v1.UserService.Login:input_type -> gophkeeper.v1.LoginRequest
	6, // 6: gophkeeper.v1.UserService.Register:input_type -> gophkeeper.v1.RegisterRequest
	3, // 7: gophkeeper.v1.AdminService.Unseal:output_type -> gophkeeper.v1.UnsealResponse
	5, // 8: gophkeeper.v1.UserService.Login:output_type -> gophkeeper.v1.LoginResponse
	7, // 9: gophkeeper.v1.UserService.Register:output_type -> gophkeeper.v1.RegisterResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_gophkeeper_proto_init() }
func file_gophkeeper_v1_gophkeeper_proto_init() {
	if File_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_gophkeeper_proto = out.File
	file_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
