// Code generated by avro/gen. DO NOT EDIT.
package card

// BankCard is a generated struct.
type BankCard struct {
	UserID         string `avro:"user_id" json:"user_id"`
	CardholderName string `avro:"cardholder_name" json:"cardholder_name"`
	CardNumber     string `avro:"card_number" json:"card_number"`
	ExpiryMonth    int    `avro:"expiry_month" json:"expiry_month"`
	ExpiryYear     int    `avro:"expiry_year" json:"expiry_year"`
	Cvv            int    `avro:"cvv" json:"cvv"`
}
