// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gophkeeper/v1/gophkeeper.proto

package gophkeeper

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_USER_ROLE_UNSPECIFIED UserRole = 0
	UserRole_USER_ROLE_USER        UserRole = 1
	UserRole_USER_ROLE_ADMIN       UserRole = 2
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "USER_ROLE_UNSPECIFIED",
		1: "USER_ROLE_USER",
		2: "USER_ROLE_ADMIN",
	}
	UserRole_value = map[string]int32{
		"USER_ROLE_UNSPECIFIED": 0,
		"USER_ROLE_USER":        1,
		"USER_ROLE_ADMIN":       2,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_gophkeeper_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type SealStatus int32

const (
	SealStatus_SEAL_STATUS_UNSPECIFIED      SealStatus = 0
	SealStatus_SEAL_STATUS_SEALED           SealStatus = 1
	SealStatus_SEAL_STATUS_PARTIALLY_SEALED SealStatus = 2
	SealStatus_SEAL_STATUS_UNSEALED         SealStatus = 3
)

// Enum value maps for SealStatus.
var (
	SealStatus_name = map[int32]string{
		0: "SEAL_STATUS_UNSPECIFIED",
		1: "SEAL_STATUS_SEALED",
		2: "SEAL_STATUS_PARTIALLY_SEALED",
		3: "SEAL_STATUS_UNSEALED",
	}
	SealStatus_value = map[string]int32{
		"SEAL_STATUS_UNSPECIFIED":      0,
		"SEAL_STATUS_SEALED":           1,
		"SEAL_STATUS_PARTIALLY_SEALED": 2,
		"SEAL_STATUS_UNSEALED":         3,
	}
)

func (x SealStatus) Enum() *SealStatus {
	p := new(SealStatus)
	*p = x
	return p
}

func (x SealStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SealStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_gophkeeper_proto_enumTypes[1].Descriptor()
}

func (SealStatus) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_gophkeeper_proto_enumTypes[1]
}

func (x SealStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SealStatus.Descriptor instead.
func (SealStatus) EnumDescriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=gophkeeper.v1.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_USER_ROLE_UNSPECIFIED
}

type UnsealServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPiece      string                 `protobuf:"bytes,1,opt,name=key_piece,json=keyPiece,proto3" json:"key_piece,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealServerRequest) Reset() {
	*x = UnsealServerRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealServerRequest) ProtoMessage() {}

func (x *UnsealServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealServerRequest.ProtoReflect.Descriptor instead.
func (*UnsealServerRequest) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *UnsealServerRequest) GetKeyPiece() string {
	if x != nil {
		return x.KeyPiece
	}
	return ""
}

type UnsealServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unsealed      bool                   `protobuf:"varint,1,opt,name=unsealed,proto3" json:"unsealed,omitempty"`
	Status        SealStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=gophkeeper.v1.SealStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealServerResponse) Reset() {
	*x = UnsealServerResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealServerResponse) ProtoMessage() {}

func (x *UnsealServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealServerResponse.ProtoReflect.Descriptor instead.
func (*UnsealServerResponse) Descriptor() ([]byte, []int) {
	return file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *UnsealServerResponse) GetUnsealed() bool {
	if x != nil {
		return x.Unsealed
	}
	return false
}

func (x *UnsealServerResponse) GetStatus() SealStatus {
	if x != nil {
		return x.Status
	}
	return SealStatus_SEAL_STATUS_UNSPECIFIED
}

func (x *UnsealServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1egophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\x1a\x1bbuf/validate/validate.proto\"X\n" +
	"\fLoginRequest\x12#\n" +
	"\busername\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x03R\busername\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\bR\bpassword\"k\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04role\x18\x03 \x01(\x0e2\x17.gophkeeper.v1.UserRoleR\x04role\";\n" +
	"\x13UnsealServerRequest\x12$\n" +
	"\tkey_piece\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bkeyPiece\"\x7f\n" +
	"\x14UnsealServerResponse\x12\x1a\n" +
	"\bunsealed\x18\x01 \x01(\bR\bunsealed\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SealStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*N\n" +
	"\bUserRole\x12\x19\n" +
	"\x15USER_ROLE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_ROLE_USER\x10\x01\x12\x13\n" +
	"\x0fUSER_ROLE_ADMIN\x10\x02*}\n" +
	"\n" +
	"SealStatus\x12\x1b\n" +
	"\x17SEAL_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEAL_STATUS_SEALED\x10\x01\x12 \n" +
	"\x1cSEAL_STATUS_PARTIALLY_SEALED\x10\x02\x12\x18\n" +
	"\x14SEAL_STATUS_UNSEALED\x10\x032\xb0\x01\n" +
	"\x11GophKeeperService\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse\x12W\n" +
	"\fUnsealServer\x12\".gophkeeper.v1.UnsealServerRequest\x1a#.gophkeeper.v1.UnsealServerResponseB\xc3\x01\n" +
	"\x11com.gophkeeper.v1B\x0fGophkeeperProtoP\x01ZHgithub.com/patraden/ya-practicum-gophkeeper/api/gophkeeper/v1;gophkeeper\xa2\x02\x03GXX\xaa\x02\rGophkeeper.V1\xca\x02\rGophkeeper\\V1\xe2\x02\x19Gophkeeper\\V1\\GPBMetadata\xea\x02\x0eGophkeeper::V1b\x06proto3"

var (
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce sync.Once
	file_gophkeeper_v1_gophkeeper_proto_rawDescData []byte
)

func file_gophkeeper_v1_gophkeeper_proto_rawDescGZIP() []byte {
	file_gophkeeper_v1_gophkeeper_proto_rawDescOnce.Do(func() {
		file_gophkeeper_v1_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)))
	})
	return file_gophkeeper_v1_gophkeeper_proto_rawDescData
}

var file_gophkeeper_v1_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(UserRole)(0),                // 0: gophkeeper.v1.UserRole
	(SealStatus)(0),              // 1: gophkeeper.v1.SealStatus
	(*LoginRequest)(nil),         // 2: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),        // 3: gophkeeper.v1.LoginResponse
	(*UnsealServerRequest)(nil),  // 4: gophkeeper.v1.UnsealServerRequest
	(*UnsealServerResponse)(nil), // 5: gophkeeper.v1.UnsealServerResponse
}
var file_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	0, // 0: gophkeeper.v1.LoginResponse.role:type_name -> gophkeeper.v1.UserRole
	1, // 1: gophkeeper.v1.UnsealServerResponse.status:type_name -> gophkeeper.v1.SealStatus
	2, // 2: gophkeeper.v1.GophKeeperService.Login:input_type -> gophkeeper.v1.LoginRequest
	4, // 3: gophkeeper.v1.GophKeeperService.UnsealServer:input_type -> gophkeeper.v1.UnsealServerRequest
	3, // 4: gophkeeper.v1.GophKeeperService.Login:output_type -> gophkeeper.v1.LoginResponse
	5, // 5: gophkeeper.v1.GophKeeperService.UnsealServer:output_type -> gophkeeper.v1.UnsealServerResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_gophkeeper_proto_init() }
func file_gophkeeper_v1_gophkeeper_proto_init() {
	if File_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_gophkeeper_proto = out.File
	file_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
