// Code generated by avro/gen. DO NOT EDIT.
package model

// UserCredentials is a generated struct.
type UserCredentials struct {
	UserID         string `avro:"user_id" json:"user_id"`
	Username       string `avro:"username" json:"username"`
	HashedPassword []byte `avro:"hashed_password" json:"hashed_password"`
}
